<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\CarModel;
use Illuminate\Database\Seeder;

class LargeCarSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::table('cars')->truncate();

        $models = CarModel::all();

        if ($models->isEmpty()) {
            $this->command->warn('No Car Models found. Please run DatabaseSeeder first.');
            return;
        }

        $carData = [
            'Corolla' => [
                'images' => ['cars/corolla.jpg'],
                'price_new' => 295000,
                'price_used' => 165000,
                'year_new' => 2024,
                'year_used' => 2019,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 45000,
            ],
            'Camry' => [
                'images' => ['cars/camry.jpg'],
                'price_new' => 380000,
                'price_used' => 220000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 35000,
            ],
            'Rav4' => [
                'images' => ['cars/rav4.jpg'],
                'price_new' => 360000,
                'price_used' => 210000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Gris',
                'mileage_new' => 0,
                'mileage_used' => 30000,
            ],
            'M3' => [
                'images' => ['cars/m3.jpg'],
                'price_new' => 950000,
                'price_used' => 520000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Bleu',
                'mileage_new' => 0,
                'mileage_used' => 25000,
            ],
            'X5' => [
                'images' => ['cars/x5.jpg'],
                'price_new' => 850000,
                'price_used' => 480000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 50000,
            ],
            'i7' => [
                'images' => ['cars/i7.jpg'],
                'price_new' => 1350000,
                'price_used' => 850000,
                'year_new' => 2024,
                'year_used' => 2023,
                'fuel_type' => 'Électrique',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 10000,
            ],
            'C-Class' => [
                'images' => ['cars/c_class.jpg'],
                'price_new' => 520000,
                'price_used' => 310000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Argent',
                'mileage_new' => 0,
                'mileage_used' => 40000,
            ],
            'G-Wagon G63' => [
                'images' => ['cars/g_wagon.jpg'],
                'price_new' => 2100000,
                'price_used' => 1450000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 15000,
            ],
            'S-Class' => [
                'images' => ['cars/s_class.jpg'],
                'price_new' => 1500000,
                'price_used' => 780000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 30000,
            ],
            'CLA 250 EQ-Technologie' => [
                'images' => ['cars/cla.jpg'],
                'price_new' => 450000,
                'price_used' => 280000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 35000,
            ],
            'A4' => [
                'images' => ['cars/a4.jpg'],
                'price_new' => 480000,
                'price_used' => 270000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Gris',
                'mileage_new' => 0,
                'mileage_used' => 45000,
            ],
            'Q7' => [
                'images' => ['cars/q7.jpg'],
                'price_new' => 820000,
                'price_used' => 480000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 55000,
            ],
            'RS3 Sportback' => [
                'images' => ['cars/rs3.jpg'],
                'price_new' => 780000,
                'price_used' => 520000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Gris',
                'mileage_new' => 0,
                'mileage_used' => 20000,
            ],
            '911 Carrera' => [
                'images' => ['cars/911.jpg'],
                'price_new' => 1450000,
                'price_used' => 950000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Rouge',
                'mileage_new' => 0,
                'mileage_used' => 20000,
            ],
            'Cayenne' => [
                'images' => ['cars/cayenne.jpg'],
                'price_new' => 1050000,
                'price_used' => 620000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 35000,
            ],
            'Taycan' => [
                'images' => ['cars/taycan.jpg'],
                'price_new' => 1200000,
                'price_used' => 780000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Électrique',
                'transmission' => 'Automatique',
                'color' => 'Bleu',
                'mileage_new' => 0,
                'mileage_used' => 15000,
            ],
            'Range Rover' => [
                'images' => ['cars/range_rover.jpg'],
                'price_new' => 1400000,
                'price_used' => 820000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 40000,
            ],
            'Defender' => [
                'images' => ['cars/defender.jpg'],
                'price_new' => 900000,
                'price_used' => 580000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Verte',
                'mileage_new' => 0,
                'mileage_used' => 25000,
            ],
            '488 Pista' => [
                'images' => ['cars/488.jpg'],
                'price_new' => 3200000,
                'price_used' => 2200000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Rouge',
                'mileage_new' => 0,
                'mileage_used' => 8000,
            ],
            'SF90 Stradale' => [
                'images' => ['cars/sf90.jpg'],
                'price_new' => 4500000,
                'price_used' => 3200000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Hybride',
                'transmission' => 'Automatique',
                'color' => 'Rouge',
                'mileage_new' => 0,
                'mileage_used' => 5000,
            ],
            'Continental GT' => [
                'images' => ['cars/continental.jpg'],
                'price_new' => 2400000,
                'price_used' => 1500000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Argent',
                'mileage_new' => 0,
                'mileage_used' => 20000,
            ],
            'Bentayga' => [
                'images' => ['cars/bentayga.jpg'],
                'price_new' => 2600000,
                'price_used' => 1650000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 25000,
            ],
            'Ghibli' => [
                'images' => ['cars/ghibli.jpg'],
                'price_new' => 920000,
                'price_used' => 520000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Bleu',
                'mileage_new' => 0,
                'mileage_used' => 40000,
            ],
            'Levante' => [
                'images' => ['cars/levante.jpg'],
                'price_new' => 1050000,
                'price_used' => 580000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Gris',
                'mileage_new' => 0,
                'mileage_used' => 35000,
            ],
            'Urus' => [
                'images' => ['cars/urus.jpg'],
                'price_new' => 2300000,
                'price_used' => 1700000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Jaune',
                'mileage_new' => 0,
                'mileage_used' => 10000,
            ],
            'Huracan' => [
                'images' => ['cars/huracan.jpg'],
                'price_new' => 2800000,
                'price_used' => 1900000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Verte',
                'mileage_new' => 0,
                'mileage_used' => 12000,
            ],
            'Golf 8 GTI' => [
                'images' => ['cars/golf.jpg'],
                'price_new' => 380000,
                'price_used' => 230000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Rouge',
                'mileage_new' => 0,
                'mileage_used' => 30000,
            ],
            'Tiguan' => [
                'images' => ['cars/tiguan.jpg'],
                'price_new' => 420000,
                'price_used' => 250000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 50000,
            ],
            'Touareg' => [
                'images' => ['cars/touareg.jpg'],
                'price_new' => 720000,
                'price_used' => 420000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Diesel',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 55000,
            ],
            'Wrangler' => [
                'images' => ['cars/wrangler.jpg'],
                'price_new' => 620000,
                'price_used' => 380000,
                'year_new' => 2024,
                'year_used' => 2021,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Verte',
                'mileage_new' => 0,
                'mileage_used' => 35000,
            ],
            'Grand Cherokee' => [
                'images' => ['cars/cherokee.jpg'],
                'price_new' => 680000,
                'price_used' => 390000,
                'year_new' => 2024,
                'year_used' => 2020,
                'fuel_type' => 'Essence',
                'transmission' => 'Automatique',
                'color' => 'Noir',
                'mileage_new' => 0,
                'mileage_used' => 50000,
            ],
            'Model S Plaid' => [
                'images' => ['cars/model_s.jpg'],
                'price_new' => 1250000,
                'price_used' => 850000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Électrique',
                'transmission' => 'Automatique',
                'color' => 'Rouge',
                'mileage_new' => 0,
                'mileage_used' => 15000,
            ],
            'Model X' => [
                'images' => ['cars/model_x.jpg'],
                'price_new' => 1100000,
                'price_used' => 720000,
                'year_new' => 2024,
                'year_used' => 2022,
                'fuel_type' => 'Électrique',
                'transmission' => 'Automatique',
                'color' => 'Blanc',
                'mileage_new' => 0,
                'mileage_used' => 20000,
            ],
        ];

        $descriptions = [
            'Corolla' => 'Toyota Corolla, sedan compacte fiable et économique. Idéale pour la ville avec sa consommation réduite.',
            'Camry' => 'Toyota Camry, sedan familiale confortable et élégante. Motorisation hybride performante.',
            'Rav4' => 'Toyota RAV4, SUV polyvalent et robuste. Parfait pour les familles et les aventures.',
            'M3' => 'BMW M3, berline sportive haute performance. Le plaisir de conduite ultime.',
            'X5' => 'BMW X5, SUV premium grand luxe. Technologie de pointe et confort exceptionnel.',
            'i7' => 'BMW i7, berline électrique 100% haute gamme. L\'avenir du luxe automobile.',
            'C-Class' => 'Mercedes-Benz C-Class, berline élégante et raffinée. Le confort au quotidien.',
            'G-Wagon G63' => 'Mercedes-AMG G63, SUV iconique tout-terrain. Puissance et prestige.',
            'S-Class' => 'Mercedes-Benz S-Class, berline de luxe flagship. La référence absolue en matière de confort.',
            'CLA 250 EQ-Technologie' => 'Mercedes-Benz CLA 250 EQ, coupé compact hybride rechargeable. Design et efficacité.',
            'A4' => 'Audi A4, berline premium au design épuré. Technologie quattro et confort.',
            'Q7' => 'Audi Q7, SUV 7 places grand luxe. Espace et technologie au rendez-vous.',
            'RS3 Sportback' => 'Audi RS3 Sportback, compacte sportive extrême. 400+ chevaux sous le capot.',
            '911 Carrera' => 'Porsche 911 Carrera, sportive de légende. Performance et iconicité.',
            'Cayenne' => 'Porsche Cayenne, SUV sportif premium. Le SUV le plus dynamique.',
            'Taycan' => 'Porsche Taycan, berline électrique sportive. Innovation et performance.',
            'Range Rover' => 'Land Rover Range Rover, SUV de luxe ultime. All-terrain et raffinement.',
            'Defender' => 'Land Rover Defender, tout-terrain iconique repensé. Aventure sans limites.',
            '488 Pista' => 'Ferrari 488 Pista, supercar de course pour la route. 720 ch de pur plaisir.',
            'SF90 Stradale' => 'Ferrari SF90 Stradale, hypercar hybride. 1000 ch, la puissance maximale.',
            'Continental GT' => 'Bentley Continental GT, grand tourisme de luxe. Opulence et performance.',
            'Bentayga' => 'Bentley Bentayga, SUV ultra-luxe. Le summum du SUV premium.',
            'Ghibli' => 'Maserati Ghibli, berline italienne au caractère affirmé. Son et passion.',
            'Levante' => 'Maserati Levante, SUV sportif italien. Élégance et dynamisme.',
            'Urus' => 'Lamborghini Urus, Super SUV. La puissance dans sa forme la plus extrême.',
            'Huracan' => 'Lamborghini Huracán, supercar V10. Design radical et performance pure.',
            'Golf 8 GTI' => 'Volkswagen Golf 8 GTI, compacte sportive iconique. Le plaisir accessible.',
            'Tiguan' => 'Volkswagen Tiguan, SUV familial polyvalent. Praticité et fiabilité.',
            'Touareg' => 'Volkswagen Touareg, SUV premium. Confort et technologie Volkswagen.',
            'Wrangler' => 'Jeep Wrangler, tout-terrain legend. Liberté et aventure.',
            'Grand Cherokee' => 'Jeep Grand Cherokee, SUV familial premium. Confort et capacités.',
            'Model S Plaid' => 'Tesla Model S Plaid, berline électrique ultra-performante. 0-100 en 2.1s.',
            'Model X' => 'Tesla Model X, SUV électrique familial. Autonomie et technologie.',
        ];

        $carsToInsert = [];

        foreach ($models as $model) {
            $data = $carData[$model->name] ?? null;

            if (!$data) {
                $data = [
                    'images' => ['cars/corolla.jpg'],
                    'price_new' => 350000,
                    'price_used' => 180000,
                    'year_new' => 2024,
                    'year_used' => 2020,
                    'fuel_type' => 'Essence',
                    'transmission' => 'Automatique',
                    'color' => 'Gris',
                    'mileage_new' => 0,
                    'mileage_used' => 40000,
                ];
            }

            $condition = $model->id % 3 === 0 ? 'occasion' : 'neuf';

            $carsToInsert[] = [
                'car_model_id' => $model->id,
                'year' => $condition === 'neuf' ? $data['year_new'] : $data['year_used'],
                'price' => $condition === 'neuf' ? $data['price_new'] : $data['price_used'],
                'mileage' => $condition === 'neuf' ? $data['mileage_new'] : $data['mileage_used'],
                'fuel_type' => $data['fuel_type'],
                'transmission' => $data['transmission'],
                'color' => $data['color'],
                'description' => $descriptions[$model->name] ?? "Véhicule " . $model->name . " en parfait état. Historique certifié APEX CAR.",
                'condition' => $condition,
                'status' => 'available',
                'images' => json_encode($data['images']),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        Car::insert($carsToInsert);

        $count = count($carsToInsert);
        $this->command->info("$count cars seeded with real prices and images!");
    }
}
